### PR TITLE
Add aliases for autowiring user and group managers

### PR DESCRIPTION
**Pull request by jvasseur**
Add aliases to allow autowiring user and groups managers with the new "id = class" convention.

### CODE REVIEW

**Comment by shakaran** [comment]
@XWB any update with this for merge it? It seems good to me

**Comment by XWB** [comment]
Thanks :)

**Comment by roberto910907** [comment]
@jvasseur @XWB What do you think about **fos_user.util.password_updater** and **fos_user.util.canonical_fields_updater**.

`Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_user.util.password_updater" service to "FOS\UserBundle\Util\PasswordUpdaterInterface" instead.`

`Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_user.util.canonical_fields_updater" service to "FOS\UserBundle\Util\CanonicalFieldsUpdater" instead.`

**Comment by iCodr8** [comment]
The alias for the TokenGenerator is missing:

```
$container->setAlias('FOS\UserBundle\Util\TokenGeneratorInterface', new Alias('fos_user.util.token_generator', false));
```

**Pull request merged**
