### PR TITLE
Prepare beta 1 release

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by XWB** [comment]
@stof Anything else?

**Comment by stof** [comment]
@XWB make it beta1 instead

**Comment by XWB** [comment]
@stof Done.

**Comment by Nek-** [comment]
Finaly \o/. Thank you very much @XWB

**Comment by Laurent3170** [comment]
Just a great thank for all the work you have achieved!

**Comment by ninsky** [comment]
Yes, **thanks** for your effort @XWB , @stof ! I think many FOSUserBundle users are stuck with Symfony 2.8 and are happy to upgrade to Symfony 3.x as soon as we have a stable FOSUserBundle 2,0 release.

**Pull request merged**
