### PR TITLE
Create FOSUserBundle.fr_FR.yml

### PR DESCRIPTION
**Pull request by DoulyCreations**

### CODE REVIEW

**Comment by stof** [comment]
We already have a `fr` locale, which is used as fallback for `fr_FR`. Is there any benefit about maintaining *different* translations for `fr_FR` ?

**Comment by DoulyCreations** [comment]
It is possible (in our case for example) not to have the translation in "fr" when we use the local "fr_FR" and not "fr".

**Comment by stof** [comment]
@DoulyCreations Symfony automatically fallbacks from `fr_FR` to `fr`.
So this is only possible if you replace the translator service and your own does not respect the behavior of the Symfony one. This is not something I want to support (as it would require duplicating translations for *all* country variants in the whole ecosystem).

If you really have such crazy logic forbidding the fallback from `fr_FR` to `fr` in your app (and you don't want to stop such thing), maintain the duplicate translation file in your own project rather than asking us to do it.

Can you give more details about your issue ?

**Comment by XWB** [comment]
This PR only makes sense if we had different French locales, like `fr_FR` and `fr_BE` etc.

**Comment by stof** [comment]
and even in this case, I would still probably keep `fr_FR` as the basis for the `fr` locale.

**Pull request closed without merging**
