### PR TITLE
Fixing Ukrainian translation for password resetting message

### PR DESCRIPTION
**Pull request by vlitovka**
Fixing Ukrainian translation. Changing parameters which was included into translation: %email% was removed, %tokenLifetime% was added.

### CODE REVIEW

**Comment by stof** [comment]
Can you also update the message changed in https://github.com/FriendsOfSymfony/FOSUserBundle/commit/1c6a2a6c01371ceb10c91779a3583cebf085cfbf ?

**Comment by vlitovka** [comment]
Sure, wil do.

**Comment by vlitovka** [comment]
I've changed a bit few words to follow general translation style. Also I've added the same note( as mentioned in commit above) to Ukrainian and Russian translation file.

**Comment by XWB** [comment]
Thanks.

**Pull request merged**
