### PR TITLE
Validates empty current password for ChangePasswordFormType

### PR DESCRIPTION
**Pull request by symfonyaml**
Relates to:
[https://github.com/symfony/symfony/pull/23341](https://github.com/symfony/symfony/pull/23341)
[https://github.com/symfony/security-core/commit/3bc0bcfeb4902e615d757f0980433dfc43befa32](https://github.com/symfony/security-core/commit/3bc0bcfeb4902e615d757f0980433dfc43befa32)

I can change user password without typing my current password.

### CODE REVIEW

**Comment by craue** [comment]
refs #2580

**Comment by craue** [comment]
This should be done against the 1.3.x branch as well. But when used with e.g. Symfony 2.7.29, two validation errors would be added with this patch (one per constraint). The same applies to #2583.

**Comment by XWB** [comment]
Thanks.

**Comment by craue** [comment]
Will 1.3 get a fix as well?

**Comment by XWB** [comment]
Perhaps someone is willing to send a PR for the 1.3 branch? I do not have 1.3 installed locally.

**Comment by craue** [comment]
Done in #2584.

**Pull request merged**
