### PR TITLE
Added basic XML Support

### PR DESCRIPTION
**Pull request by WouterJ**
I'm not so sure about the namespace, if you can come up with a different (better) one, I'll change it.

### CODE REVIEW

**Comment by WouterJ** [comment]
One year later, is there any reason not to merge this?

**Comment by merk** [comment]
:+1:

**Comment by stof** [comment]
@WouterJ can you rebase it to put the changelog in the right place (if we merge it now, it would end up in the changelog of the 2.0-alpha1 release, which will be wrong)

**Comment by WouterJ** [comment]
@stof done

**Comment by stof** [comment]
It took time, but here we go, this is in now. Thank you very much @WouterJ.

**Pull request closed without merging**
