### PR TITLE
checkPreAuth() missing

### PR DESCRIPTION
**Pull request by danielsan80**
checkPreAuth() method avoid locked and disabled user will be logged in

### CODE REVIEW

**Comment by XWB** [comment]
This was already fixed in 2.0, see https://github.com/FriendsOfSymfony/FOSUserBundle/commit/8fd37fa80a84fe4a6b48403e618ee3da73db2b92

**Comment by danielsan80** [comment]
Sorry, so 1.3.x version is no more supported? I'm not sure about this, but I think some FOS bundles (depending on FOSUserBundle) do not still work with 2.0.x version.

**Comment by XWB** [comment]
> I think some FOS bundles (depending on FOSUserBundle) do not still work with 2.0.x version.

@danielsan80 What bundles would that be?

**Comment by danielsan80** [comment]
@XWB I checked the project when I had the problem. FOSOAuthServerBundle 1.5.2 seams to have some problem with the FOSUserBundle 2.0.x version.

It give me the following error:

`Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given`

It seams OAuthStorage still depends on UserProviderInterface but the 2.0 UserManager doesn't implement it any more.

I've thought OAuthServerBundle was not still stable enough with FOSUserBundle 2.0, so I used the 1.3 version, wainting for a better moment.

**Pull request closed without merging**
