### PR TITLE
fixed UserProvider::refreshUser() not checking the class-name

### PR DESCRIPTION
**Pull request by he-li**
Hello,

I ran into this bug today, and this commit fix it.
Could you merge this into 1.3?

Thanks

### CODE REVIEW

**Comment by stof** [comment]
What is the bug exactly ?

**Comment by sstok** [comment]
This was already fixed with https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1239
But from what I understand its also present in the 1.3 branch.

**Comment by he-li** [comment]
Yes exactly, I just picked the same commit there and applied to the 1.3 branch.

**Comment by sstok** [comment]
Ah :) the master branch is not up-to-date with 1.3 branch.

:+1: from me then.

**Comment by XWB** [comment]
Fixed in 1.3 as well https://github.com/FriendsOfSymfony/FOSUserBundle/commit/1d9dac659af8fafc4767ea046cce6be325822d2a

**Pull request closed without merging**
