### PR TITLE
[Travis] update Symfony version

### PR DESCRIPTION
**Pull request by xabbuh**
We have a stable release for Symfony 2.7 now.

### CODE REVIEW

**Comment by xabbuh** [comment]
seems like there are some event dispatcher related things that should be updated

**Comment by stof** [comment]
Yeah, the code does not use the deprecated features anymore when the event dispatcher is passed in the new way, but tests are not passing it

**Comment by xabbuh** [comment]
@stof Indeed, I think it's okay to silence deprecation warnings for these two particular tests. What do you think?

**Comment by stof** [comment]
I'd rather fix the tests themselves to pass the event name the proper way

**Comment by xabbuh** [comment]
How would you do that? I don't see a way to detect which version of the EventDispatcher component is installed.

**Comment by xabbuh** [comment]
ping @stof Any idea?

**Comment by XWB** [comment]
See https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1928

**Pull request closed without merging**
