### PR TITLE
Change Travis to GitHubActions

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
@stof in this pr - see all check is green -> https://github.com/Yozhef/FOSUserBundle/pull/1

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Is this ready to merge?

**Comment by Yozhef** [comment]
@OskarStark yes.

**Comment by VincentLanglet** [comment]
Friendly ping @stof , I saw (https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2998#issuecomment-788064930) that some maintenance is wanted to add the support of Symfony 5. Support of PHP8 could be great too.

There is multiple PR trying to add these supports which are opened, I assume you don't have a lot of time. Do you need some help ? Maybe sharing right with @OskarStark ?

**Comment by OskarStark** [comment]
@stof we also need this here https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/2853#issuecomment-813277931

to be able to support PHP 8 for KuntsmaanBundle

cc @acrobat

**Pull request merged**
