### PR TITLE
Update FOSUserBundle.fr.yml

### PR DESCRIPTION
**Pull request by gautierderuette**
better french translation for password_confirmation

### CODE REVIEW

**Comment by Laurent3170** [comment]
In fact "du" is removed to make it shorter and consistant with "Confirmation nouveau mot de passe" which is without "du"

**Comment by Laurent3170** [comment]
Have a look at #2268

**Comment by gautierderuette** [comment]
Ok I should have modified the two translations but without 'du' the sentence is wrong

**Comment by Laurent3170** [comment]
In my point of view it's not really wrong as it can be understand as an instruction. As I said, I have removed them, when I have edited the file, because it's 3 letters less which is good when displaying on small devices...

**Comment by gautierderuette** [comment]
Ok I don't insist. Do you know why the continuous_integration failed ?

**Comment by Laurent3170** [comment]
It's not a matter of insisting, we can discuss ;-) I have just explained why I've removed them.
For the continuous integration, no I don't know

**Comment by gautierderuette** [comment]
Ok, so my point of view is that the sentence must be the most grammatically correct and then we can custom it for specific needs (as small devices). How do we decide ?

**Comment by Laurent3170** [comment]
It is grammatically correct and having to customize it for specific needs, I don't think it's a solution... As you will have a text on tablets and another one on smartphones.
I don't know how to agree ;-) I prefer to keep it short as it's still good french.

**Comment by Laurent3170** [comment]
https://translate.google.fr/?hl=fr#en/fr/password%20confirmation

**Comment by gautierderuette** [comment]
haha ok you won :)

**Comment by Laurent3170** [comment]
Maybe not ;-) in the english https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/translations/FOSUserBundle.en.yml they use "Repeat password"

**Comment by Laurent3170** [comment]
Confirmation mot de passe --> Répéter mot de passe
Confirmation nouveau mot de passe --> Répéter nouveau mot de passe
are even shorter !
If you agree I let you modify your commit

**Comment by gautierderuette** [comment]
And what about 
"Répéter le mot de passe" and
"Répéter le nouveau mot de passe" ? ;-)

**Comment by Laurent3170** [comment]
I don't think we need "le", still because it's an instruction, but as it's still shorter than "Confirmation...". I agree.

**Comment by stof** [comment]
The test failure is because Symfony 3.2.0 got released, but FrameworkBundle removed some dependencies, moving them to optional ones. We need to update the list of our dev requirements instead of relying on transitive deps from FrameworkBundle.

**Comment by stof** [comment]
thanks for this change though

**Pull request merged**
