### PR TITLE
FixBug: Find users with a "username" that looks like an email address => e.g. "myUserNameWithAn@AndA.InIt"

### PR DESCRIPTION
**Pull request by azine**
Hi,

I want to fix the following scenario:

A user registered with the username "mymail@email.com" and the email address "mymail@email.com". 
Later that user edits his/her profile and changes his email to "myotheremail@email.com" (or (s)he uses two different email-addresses already when registering). 

So there is a user with "mymail@email.com" as username and "myotheremail@email.com" as email.

With the current implementation of the UserManager, this user will not be able to login with his/her username.

This pull-request tries to fix this.

Cheers,
Dominik

### CODE REVIEW

**Comment by azine** [comment]
@lsmith77 or @stof: what is the reason you didn't accept my proposed fix for this error in the fosuserbundle? 

(The travis-build & scritinizer were fine at that time!!)

**Comment by JHGitty** [comment]
rel #1923

**Comment by XWB** [comment]
We should find another way to fix this.

https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1923

**Comment by azine** [comment]
Hi XWB,

#1923 is not related to this issue!!

#1923 is about validating a string as being a correct email or not

this bug is about a user using a username-string that looks like an email, while using another valid email for his/her email-field. 

Solving #1923 won't fix this issue.  The solution for this issue is SIMPLE and I proposed a fix for it two years ago.

What do you think is wrong with my proposed solution?

Cheers,
Dominik

**Comment by JHGitty** [comment]
You are right: Solving #1923 will not solve this issue but it is a little bit related to it.
This issue is an edge-case. I don't know how we could ever fix it.

For example we have 4 users:
1. User "Tom" with email "tom@tom.com"
2. User "tom@tom.com" with email "tom@gmail.com"

Which user should be selected if the input for username is 'tom@tom.com'?
What is the best way? What do you like?

**Comment by azine** [comment]
Hi JHHGitty,

thanx for your answer. You've got a point.

Thanx for opening the other issue.

Cheers,
D.

**Comment by azine** [comment]
fixed with #2650

**Pull request closed without merging**
