### PR TITLE
New rounting files for Symfonyf4.1

### PR DESCRIPTION
**Pull request by axzx**
Similar to https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2806, but developer have to use the right version for his Symfony. 

Change `:` to `::` for controller actions for hide deprecations about this.

### CODE REVIEW

**Comment by XWB** [comment]
Thanks.

**Comment by stof** [comment]
but this means we will have `routing_41` in the future, even when dropping support for older versions of Symfony :cry:

**Comment by stof** [comment]
Before making a new release containing that PR, I want to see the result of the Symfony PR referenced just above this comment, as this PR might become unnecessary (and then should be reverted before the release to avoid BC concerns on that new file)

**Comment by XWB** [comment]
We should find out with the next Symfony 4.1 release.

**Pull request merged**
