### PR TITLE
Added Event before requesting password recovery

### PR DESCRIPTION
**Pull request by ricohumme**
A check to not let a user request a password when locked out.

### CODE REVIEW

**Comment by ricohumme** [comment]
Hi, any thought as to when this will be processed ?

**Comment by xabbuh** [comment]
You should at least revert the permission changes. These files don't need to be executable.

**Comment by ricohumme** [comment]
Thanks for the heads up. I'll fix that in my system right away so it doesn't happen again

**Comment by cinamo** [comment]
I'd love to have this, too!

**Comment by XWB** [comment]
Thanks.

**Comment by ricohumme** [comment]
Thanks for merging :D

**Pull request merged**
