### PR TITLE
setFactoryMethod is deprecated

### PR DESCRIPTION
**Pull request by tarjei**

### CODE REVIEW

**Comment by tarjei** [comment]
The fix is needed for 2.7 compability.

**Comment by gnutix** [comment]
Isn't there even more files that need to be updated ? I have warnings in:
* profile.xml
* registration.xml
* change_password.xml
* resetting.xml
* group.xml

**Comment by stof** [comment]
your change is a no-go as it drops the support of Symfony 2.3 LTS.

Note that FOSUserBundle dev-master runs on 2.7 without deprecation notices

**Comment by tarjei** [comment]
But dev-master is not something you want to run in production. Do you have
an idea on how to square that circle?

2015-06-05 12:02 GMT+02:00 Christophe Coevoet <notifications@github.com>:

> your change is a no-go as it drops the support of Symfony 2.3 LTS.
>
> Note that FOSUserBundle dev-master runs on 2.7 without deprecation notices
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1852#issuecomment-109246363>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by tarjei** [comment]
Is it an option to keep two sets of config files and have a check in the
loader that decides wich to load?

2015-06-05 12:35 GMT+02:00 Tarjei Huse <tarjei.huse@gmail.com>:

> But dev-master is not something you want to run in production. Do you have
> an idea on how to square that circle?
>
> 2015-06-05 12:02 GMT+02:00 Christophe Coevoet <notifications@github.com>:
>
>> your change is a no-go as it drops the support of Symfony 2.3 LTS.
>>
>> Note that FOSUserBundle dev-master runs on 2.7 without deprecation notices
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1852#issuecomment-109246363>
>> .
>>
>
>
>
> --
> __________________
> Tarjei Huse
> Mobil: 920 63 413
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by stof** [comment]
technically, I'm running the 2.0.x-dev version of FOSUserBundle in production since years (and I know many other people do too). I hope to release it soon though.

Using different files is a no-go as well. It would be a huge nightmare to maintain. Thus, it is not the only place where FOSUserBundle 1.3.x relies on APIs deprecated between 2.3 and 2.7.

I will evaluate this weekend how much work is needed before releasing 2.0. If it would take too much time, I would backport the changes done in master for deprecations to the 1.3.x branch. Anyway, I'm closing this PR as it is not the right way to solve things.

**Pull request closed without merging**
