### PR TITLE
Remove propel dependency

### PR DESCRIPTION
**Pull request by core23**
We should drop propel for the next stable release, because there is no running version of it. Refs https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2224

This dependecy could be added later if we have a working solution.

### CODE REVIEW

**Comment by XWB** [comment]
Just out of curiosity, why can't we fix Propel 1.x support?

**Comment by stof** [comment]
@XWB the issue is that Propel support forces us to have broken classes in the repo for people not using Propel (as the base class is not generated), which causes issues for tools loading classes (like the new annotation cache warmer)

What I would do is extract the Propel integration to a separate bundle (and ask for maintainers for it, to have a maintainer actually using Propel).
I have a WIP locally for this.

**Comment by core23** [comment]
> Just out of curiosity, why can't we fix Propel 1.x support?

ATM we have no maintainer for propel, so we can't release a stable release.

**Comment by stof** [comment]
btw, this PR is not removing the propel dependency. It is removing the propel integration (and so removing a feature)

**Comment by weaverryan** [comment]
👍 for removing it. And I don't think we need to re-add into a separate bundle now: if someone needs it and has some time to volunteer, they can take the code from this PR and create that bundle then.

**Comment by OskarStark** [comment]
> if someone needs it and has some time to volunteer, they can take the code from this PR and create that bundle then.

👍

**Comment by XWB** [comment]
Well @stof is right, we would be removing a feature. On the flip side, propel hasn't been updated since 2014. It's difficult to keep supporting an outdated feature. What do you think about removing propel support, @stof ?

**Comment by core23** [comment]
Maybe ask twitter who is using it?

**Comment by XWB** [comment]
Maybe https://github.com/symfony/symfony/pull/20559 will fix the validator issue.

**Comment by XWB** [comment]
Everyone seems to agree on removing Propel support => merged.

**Comment by simmstein** [comment]
You broke many of applications with this merge…you can't brake the API like this!

**Comment by OskarStark** [comment]
> You broke many of applications with this merge…you can't brake the API like this!

you should not depend on `master`, sorry for that, you can pin to specific commit to get your apps back to life!

**Comment by simmstein** [comment]
Come on, how can I get fixes? If you want to drop propel, create a new major version. 
Propel is not use as mush as Doctrine but developpers use it and you must keep it on fosuser.

**Comment by stof** [comment]
@simmstein the master branch is precisely the dev version of FOSUserBundle 2.0, which *is* a new major version

**Comment by stof** [comment]
And as discussed in the issue, the propel integration will be kept in a separate bundle (I started it locally). But keeping it in the repo itself was causing issues for non-Propel users due to the fact that the Propel model extends a base class generated by Propel, which does not exist when you don't use Propel.

**Comment by simmstein** [comment]
Sorry but v2.0.0-alpha2 contains Propel so v2.0.* should contains propel. I can't use the version 1.3 because of your `SecurityController` and the method `loginAction` which not get the `request` from a parameter.

**Comment by XWB** [comment]
Breaking changes are allowed between alpha versions.

Of course, you could always send a PR with a working Propel2 solution. We would be happy to have an active Propel maintainer.

**Comment by simmstein** [comment]
So you said "fuck off propels users" with 2 votes and you dropped propel from a development started in 2014…You must be aware that developments have been made since 2 years. I can't believe it.

**Comment by stof** [comment]
@simmstein the alpha2 release does not contain all BC breaking changes done in 2.0. This is why it is an alpha release.
And if you look at releases, we haven't tagged a release with the propel removal yet either. So if you use our alpha releases, you will still have it (and when we make the next release, we will document the upgrade path for Propel users).

Btw, if you just need access to the request in your controller, you can use the ``request_stack`` service to access it.

**Comment by OskarStark** [comment]
And as @stof said:
> And as discussed in the issue, the propel integration will be kept in a separate bundle (I started it locally).

**Comment by XWB** [comment]
The last Propel commit dates from [April 2014](https://github.com/propelorm/Propel/commits/master), more than 3 years ago (!). And Propel2 was never supported.

**Comment by simmstein** [comment]
And from 2014 to few days, propel was supported and worked. As I said : you must be aware that developments have been made since 2 years.

**Comment by stof** [comment]
@simmstein And again, we **know** this. But if you update to dev versions even before we release them, you are on your own. The separate bundle providing a propel integration will get an alpha release before the next alpha release of FOSUserBundle to allow propel users to upgrade to the new alpha.

**Comment by XWB** [comment]
> And from 2014 to few days, propel was supported and worked.

Propel support was broken since September ([click](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2224)).

**Comment by simmstein** [comment]
Symfony version 3.2.x-dev.

Anyway…

**Comment by XWB** [comment]
Symfony 3.2 will be released soon.

**Comment by stof** [comment]
@XWB your comment is wrong. It was not propel support being broken. It was the propel integration breaking things for *all non-Propel users* on Symfony 3.2

And this is precisely why we are moving this to a separate bundle

**Comment by stof** [comment]
@simmstein the Propel integration for FOSUserBundle 2 is now at https://packagist.org/packages/friendsofsymfony/propel1-user-bundle

**Comment by simmstein** [comment]
Thanks, I gonna test!

**Comment by XWB** [comment]
Nice job @stof

**Pull request merged**
