### PR TITLE
Added travis config for symfony 3.1

### PR DESCRIPTION
**Pull request by core23**
We should test symfony 3.1, which was [release in may](https://symfony.com/blog/symfony-3-1-0-released).

### CODE REVIEW

**Comment by XWB** [comment]
Actually we are already testing Symfony 3.1 as Travis also installs the latest Symfony version.

**Comment by xabbuh** [comment]
I suggest to revert this change. This combination is already included by the PHP 5.6 build. Adding this entry adds an unnecessary build that slows down all other builds in the FriendsOfSymfony organisation.

**Comment by XWB** [comment]
That's only temporary, Symfony 3.2 will be released next month.

**Comment by stof** [comment]
@XWB and then, 3.1 will reach end of support very soon after that. I suggest adding specific jobs only for LTS versions

**Comment by XWB** [comment]
Fair enough.

**Comment by XWB** [comment]
@stof  https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2263

**Pull request merged**
