### PR TITLE
Closer match to the Security Docs showing Algorithm

### PR DESCRIPTION
**Pull request by BallisticPain**
Showed the security.yml configuration options more similarly to the Security documentation.

### CODE REVIEW

**Comment by OskarStark** [comment]
i would keep the short version, but add a notice for the ``cost/algorithm`` keys

**Comment by BallisticPain** [comment]
I'm good with keeping the short version and adding a comment or note about the `cost` and `algorithm` keys, could even reference the Security docs.

**Comment by stof** [comment]
I'm not even sure we need to add a note for the extra config options. We are not responsible for documenting all the features of SecurityBundle.

**Comment by XWB** [comment]
I agree with @stof

**Pull request closed without merging**
