### PR TITLE
remove code that was only needed for symfony 2.2 and older

### PR DESCRIPTION
**Pull request by dbu**
i just noticed that this BC code was still here - as far as i can tell, it was never used anymore since we raised the minimal version of symfony to 2.3.

### CODE REVIEW

**Comment by lsmith77** [comment]
+1

**Comment by XWB** [comment]
:+1:

**Comment by dbu** [comment]
thanks @XWB

**Comment by xabbuh** [comment]
This change makes the bundle incompatible with releases of DoctrineBundle before 1.3 (see https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2109#issuecomment-207766460). What do you think if we added a check in the `Configuration` class that provided a meaningful error message when the installed version of the DoctrineBundle is too old?

**Comment by dbu** [comment]
or a 'conflicts' in composer.json?

and sorry that i did not notice that one. we seem to miss a minimal version
test run.

**Comment by dbu** [comment]
i notice that require-dev already has doctrine-bundle as ~1.3 so i think
we just miss a conflicts section. is that corrects?

**Pull request merged**
