### PR TITLE
Fixed wrong parent call

### PR DESCRIPTION
**Pull request by core23**
The properties and methods exists in the parents parent class `UserEvent

### CODE REVIEW

**Comment by XWB** [comment]
I suppose we can entirely remove `GetResponseNullableUserEvent`?

**Comment by core23** [comment]
If we have no special usage at all.

**Comment by OskarStark** [comment]
If i remember correct, this was introduced in one of the last PR's

**Comment by XWB** [comment]
Correct. It's better to remove `GetResponseNullableUserEvent` then.

**Comment by OskarStark** [comment]
But it was used to fix a bug and here `UserInterface $user = null` null is allowed...

**Comment by core23** [comment]
This is a better fix now

**Comment by XWB** [comment]
Thanks.

**Comment by stof** [comment]
I'm -1 for switching to protected visibility. It forces us to maintain BC on these properties.

**Comment by XWB** [comment]
@core23 Was there a practical reason to change the visibility?

**Comment by core23** [comment]
> @core23 Was there a practical reason to change the visibility?

We have have the same properties in both classes, so why shouldn't we use the same protected properties?

**Pull request merged**
