### PR TITLE
Change : to :: for controller method (deprecated for 4.1)

### PR DESCRIPTION
**Pull request by mazarini**
Suppress deprecated messages and fix a php-cs-fixer message

### CODE REVIEW

**Comment by stof** [comment]
that's dropping support for old older versions of Symfony. That's not something we can do yet.

**Comment by BackEndTea** [comment]
I have seen other bundles create a separate 4.1+ list of routes. That does mean that as long as versions below 4.1 are supported every update done to those files has to be done twice.

**Comment by sharif9876** [comment]
@stof do we have to override the routes ourselves then if using 4.1? The deprecation is currently not allowing phpunit to pass for my project

**Comment by pscheit** [comment]
there is an env var to disable deprecation warnings in phpunit

**Comment by Tomsgu** [comment]
@stof Would solution of @BackEndTea (https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2806#issuecomment-411046941) be acceptable here or we should wait until 2.8 will be dropped?

**Comment by kubk** [comment]
This warning makes my development log unreadable because of a lot of deprecation warnings.

@Tomsgu Setting `SYMFONY_DEPRECATIONS_HELPER=weak` is not acceptable because it only hides the deprecation instead of fixing it.

**Comment by kubk** [comment]
@stof What do you think about creating separate xml files for Symfony 4.1+? Example: https://github.com/hwi/HWIOAuthBundle/pull/1397

**Comment by kubk** [comment]
@Tomsgu Sorry, you are right.

Also I agree with you about different routing files, for me it solves the problem.

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2853

**Pull request closed without merging**
