### PR TITLE
Use new security error helper in login action

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Use a new helper to drastically reduce the code used in the login form actions, [new for Symfony 2.6](http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements#added-a-security-error-helper)

### CODE REVIEW

**Comment by stloyd** [comment]
To use that code you would need to update min. version of Symfony in `composer.json`...

**Comment by merk** [comment]
Seems logical to me to use this helper if it exists, but :-1: to bumping requirement to 2.6

**Comment by bocharsky-bw** [comment]
There is a major `v.2.0.0-alpha1` version increase of `FOSUserBundle` already. Maybe it should be used for this major release?
P.S. I think it will not be implemented soon if not use it now.

**Comment by merk** [comment]
We wont be breaking support for LTS 2.3 until v3 of this bundle at the earliest

**Comment by stof** [comment]
Closing as we indeed won't remove the support for the LTS until its end of support. Given this logic works fine here (AFAIK, it was taken from here to create the new helper), it is OK to keep it for now.

**Pull request closed without merging**
