### PR TITLE
replace UserChecker checkPostAuth by checkPreAuth in LoginManager

### PR DESCRIPTION
**Pull request by hellomedia**
Bug fix: yes
Feature addition:  no
Backwards compatibility break: no
Fixes the following tickets: #1413 

The checks against login in are in [userChecker checkPreAuth]( https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/User/UserChecker.php ), not checkPostAuth , since the content of those 2 checks was fixed in https://github.com/symfony/symfony/pull/9902.

### CODE REVIEW

**Comment by nescim** [comment]
I'm a bit surprised this change hasn't been merged yet. Is it because the situation has been already covered by another merge?
I don't think the dilemma about the meaning of locked/enabled should block progress here. There has to be SOME way to block users short of deletion or removing their emails from the DB.

At present the semantical meaning of the flags in the bundle seems to be that locked is an administrative banning measure and enable is for email verification, as proved by the fact that resetting your password toggles the enabled flag.
I believe the bundle should make a security update in line with this interpretation (i.e. blocking locked users form resetting their password). If the other interpretation is to be preferred (as is likely) it will be possible to change that together with a new behavior for the enabled flag.

**Comment by hellomedia** [comment]
I suppose it got unnoticed or forgotten. I would love to hear from fosuser bundle admins about this PR. It seems like a simple change that fixes a non-trivial security issue.

**Comment by hlecorche** [comment]
:+1:

**Comment by hellomedia** [comment]
@stof when you have a sec can you give a feedback on this PR or point me to someone who could ? It's fairly straightforward and fixes a security issue.

**Comment by peshi** [comment]
:+1:

**Comment by peshi** [comment]
I can't believe translations are coming first hand...

**Comment by whitewhidow** [comment]
sssoooooo ..   would merging this fix the fact that locked and disabled users can still reset and login ..?

**Comment by peshi** [comment]
@whitewhidow The users can't login if the account is locked or expired. They can however login if the account has been 'disabled' only, due to this line of code.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/EventListener/ResettingListener.php#L54

**Comment by whitewhidow** [comment]
but at the moment,   a LOCKED user,   can still perform a pass reset and end up logged in, correct ?

**Comment by nescim** [comment]
exactly

**Comment by hellomedia** [comment]
@sstok can we have some feedback on this ?

**Comment by sstok** [comment]
Seems good to me :+1:

**Comment by hellomedia** [comment]
@sstok thanks. anything I can do to speed up the merging process ? should I ping someone ?

**Comment by sstok** [comment]
@hellomedia You need to rebase as there is a conflict.

**Comment by hellomedia** [comment]
@sstok and should I send the PR to master, 1.3 or 1.2 ? The issue exists in all branches.

**Comment by sstok** [comment]
Not sure, but if you rebase on the master @stof should be able to merge into an older branch (when needed).

**Comment by whitewhidow** [comment]
here is a mergeable one : https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1834 , hoping to speed things up

**Comment by hellomedia** [comment]
@sstok OK so I rebased and tried to go another route than @whitewhidow . I removed the test for isEnabled and added a test for the loginManager. however this test fails : 

    Expectation failed for method name is equal to <string:checkPreAuth> when invoked 1 time(s). Method was expected to be called 1 times, actually called 0 times.

It seems to me like the method is called, I must be missing something. TBH I am not very familiar with tests yet so any tips would be appreciated :)

**Comment by Gremlyn** [comment]
Any further update on this? ust ran into this today when adding an admin approval step and found that successful confirmation through email allowed my users to still log in. I added my check to the checkPostAuth to make it work for now, but fixing this whole issue in general would be ideal.

**Comment by clytemnestra** [comment]
Any update on this? It's really one line of code.

**Comment by xawiers** [comment]
They use sleeping pils.
Alo, fix that line. Now locked users still can login.

**Comment by xawiers** [comment]
What I did to solve this problem:
```
parameters:
#    parameter_name: value
    fos_user.security.login_manager.class: AppBundle\Security\LoginManager
```

copy original FOS login manager to own app and "fix" code:
```
    final public function logInUser($firewallName, UserInterface $user, Response $response = null)
    {
        $this->userChecker->checkPreAuth($user);
        $this->userChecker->checkPostAuth($user);

        $token = $this->createToken($firewallName, $user);

        $request = null;
...
```

clear cache, test

Now locked user can change password but can't login.

**Comment by clytemnestra** [comment]
I've used this workaround, much cleaner: https://medium.com/@sskorc/fosuserbundle-security-hole-d229667e7c22#.svqtjirbo

**Comment by xawiers** [comment]
Does it work correctly on enabled but locked user?
Removing line `$user->setEnabled(true);` on already enabled user does no effect.

My case is following: When user registers gets `enabled=false` and `locked=true` User has to confirm his email (enabled false -> true) and I have to confirm his data (locked true -> false)

**Comment by clytemnestra** [comment]
Indeed my solution doesn't work, but I don't get it how you override logInUser, because it is declared final.

**Comment by cmodijk** [comment]
@clytemnestra I think he did not extend it but just made a copy of it. We did the same thing..

**Comment by xawiers** [comment]
Yes, i did not extend, i override defined parameter in service:
```
parameters:
  fos_user.security.login_manager.class: AppBundle\Security\LoginManager
```
by default FOS UB uses own LoginManager, I copy to own namespace and update one function. You have to keep in mind to restore it after updating FOS UB (via composer update or similar) and if that update contains fixed code.

**Comment by kolinko-ant** [comment]
Guys, any updates here? why this PR can not be merged?

**Comment by damianprzygodzki** [comment]
It's major security issue! Why it is not merged yet?

**Comment by XWB** [comment]
Closing this in favor of https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2210

**Pull request closed without merging**
