### PR TITLE
Symfony 5 phpunit 9.5.2 PHP8 support

### PR DESCRIPTION
**Pull request by evrinoma**
Hi
Bundle was tested on php version 80, 74 successfully
Fixed the deprecation of usage Templating
Fixed doctrine ObjectManager deprecation
Fixed EventDispatcher deprecation
Fixed Tests
Fixed travis see (https://symfony.com/doc/master/bundles/best_practices.html)
Completed code refactoring
Removed doctrine restrictions and update php version in composer 
Fixed User Deprecated: Since symfony/http-kernel 5.1: Referencing controllers with a single colon is deprecated.

update PHP version 8.0
update phpunit 9.5.2
travis CI support Symfony version 4,5
creat scrutinizer-ci configuration

update travis CI configuration 
if you used symfony < 5.3 in project please use commit_id 10db25074bb4f7fcd4e7982020eeeae3273159cd or tag version 2.1.3
or composer require evrinoma/user-bundle:2.1.3

### CODE REVIEW

**Comment by eerison** [comment]
Well I think we can assume this PR won't pass https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2874#issuecomment-616178601

and since from 03.2020, there isn`t any merge 😕

**Comment by evrinoma** [comment]
update PHP version 8.0
update phpunit 9.5.2
travis CI support Symfony version 4,5

**Comment by 4c0n** [comment]
@stof It seems that what you were talking about here: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2998#issuecomment-788064930

has been done in this PR.
We all understand we shouldn't use this in new projects, however we unfortunately do have old projects to maintain that for example use the Sonata admin bundle for example (which is now stagnating because this bundle is). Could you please take the time to review this, so that we can move forward with this?

**Comment by evrinoma** [comment]
> This parameter type is incoherent with the `instanceof` tests that occur a few lines under.
Hi Quentint. 
what type $om you've got?

**Comment by JarJak** [comment]
@evrinoma your fork now breaks compatibility with Security component/bundle <5.3 by using UserNotFoundException which is a new thing in 5.3 https://github.com/evrinoma/FOSUserBundle/commit/f5034901589c4ea36d4c1a326030cecedb79090a

**Comment by evrinoma** [comment]
> @evrinoma your fork now breaks compatibility with Security component/bundle <5.3 by using UserNotFoundException which is a new thing in 5.3 [evrinoma@f503490](https://github.com/evrinoma/FOSUserBundle/commit/f5034901589c4ea36d4c1a326030cecedb79090a)

Hi JerJak
Thanks for you question. I know about it, but now all my projects based on version 5.3. 
Sorry I can't make stable release marked different tags.  But you still could use stable commit 10db25074bb4f7fcd4e7982020eeeae3273159cd

**Comment by JarJak** [comment]
@evrinoma can you upgrade composer.json to match minumum security bundle version then?

**Comment by evrinoma** [comment]
> @evrinoma can you upgrade composer.json to match minumum security bundle version then?

why should I to do it?
we have setted composer symfony bundles as 5.0 and I suppose next value will be 6.0

**Comment by JarJak** [comment]
> why should I to do it?
Because persons which are using your bundle will be alerted that there is BC break when they run composer update.
> as you can see ... the bundle was build successfully for different version symfony
Well it builds up, but do you have the newly added deps covered by your tests? Because if you would then those tests will fail.

I can see you have recently added password hasher dependency, which is another new thing in Symfony (introduced in v5.3 afair) - by setting up minimum required version persons like ma will be able to avoid runtime errors because composer will warn them at compile time.

**Comment by evrinoma** [comment]
> > why should I to do it?
> 
> Because persons which are using your bundle will be alerted that there is BC break when they run composer update.
> 
> > as you can see ... the bundle was build successfully for different version symfony
> 
> Well it builds up, but do you have the newly added deps covered by your tests? Because if you would then those tests will fail.
> 
> I can see you have recently added password hasher dependency, which is another new thing in Symfony (introduced in v5.3 afair) - by setting up minimum required version persons like ma will be able to avoid runtime errors because composer will warn them at compile time.

ok I see... if you are using symfony less 5.3 than please try to use next command git checkout tags/2.1.3 -b 2.1.3 or git checkout 10db25074bb4f7fcd4e7982020eeeae3273159cd

**Comment by stof** [comment]
Closing in favor of #3020 (and previous ones)

**Comment by evrinoma** [comment]
Hi Stof
I'm sorry but current version have a problems
https://github.com/evrinoma/test/runs/3498876209

**Pull request closed without merging**
