### PR TITLE
Update SecurityController.php

### PR DESCRIPTION
**Pull request by sgb004**

### CODE REVIEW

**Comment by core23** [comment]
Why?

**Comment by eduardoconceicao** [comment]
Shouldn't this PR also change the view? (Since you're passing the form view to it)

**Comment by sgb004** [comment]
core23, because with this code you can use form_row and form_widget, your login form can keep the design of your proyect without repeat html in login_content.html.twig

**Comment by sgb004** [comment]
eduardoconceicao of course, I edited login_content.html.twig, you can check in:
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2393/commits/6a82e46ee4eb67445666827492dc4a36c3875ea5
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2393

**Comment by eduardoconceicao** [comment]
@sgb004 I think that it would make more sense if the 2 commits were in the same PR but it will work anyway if they will be merge at the same time

**Comment by sgb004** [comment]
@eduardoconceicao sorry, also I forgot to put:

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

in the first PR.

**Comment by core23** [comment]
Please make ONE PR with this feature. not two https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2393/files

**Comment by sgb004** [comment]
Oh!, yes, it's only one PR to login_content.html.twig https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2393

**Comment by XWB** [comment]
AFAIK this won't work on Symfony 2.7

**Pull request closed without merging**
