### PR TITLE
Redirect to login when using confirmation token already used or not found

### PR DESCRIPTION
**Pull request by benjaminb-**
See #2763

### CODE REVIEW

**Comment by benjaminb-** [comment]
I don't understand why Travis build failed !

**Comment by stof** [comment]
Why should we redirect to login in this case ?

**Comment by benjaminb-** [comment]
In my opinion it should because users Can click more than once, on the email confirmation link and get redirected to the 404. They think something is broken, happens to every app i develop.

**Comment by benjaminb-** [comment]
Also a previous pull request concerning the resetting email link was merged : 

https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2675

I know we can override the controller, but just for that it seems it could be simpler.

As you want guys :)

**Comment by benjaminb-** [comment]
anyone ? :)

**Comment by XWB** [comment]
I'm fine with this change. At least it makes the behavior consistent with `RegistrationController::checkEmailAction`.

@benjaminb- Can you address the CS issue:

> 1) Controller/RegistrationController.php (no_unused_imports)

**Comment by XWB** [comment]
@benjaminb- Something must have gone wrong, the entire PR became something different.

**Comment by benjaminb-** [comment]
@XWB ok sorry i pushed a merge of master, i cleaned my pull request, only my 2 commits are here now :)

**Comment by benjaminb-** [comment]
@XWB can you please review ? :) Thanks !! ;)

**Comment by XWB** [comment]
Thanks :)

**Pull request merged**
