### PR TITLE
Remove unused %email% part from hungarian resetting.check_email translation

### PR DESCRIPTION
**Pull request by peterbxyz**
The new translation represents the current english text without the '%email%' part.

### CODE REVIEW

**Comment by stof** [comment]
Can you also update the translations for changes done in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2400 ?

**Comment by stof** [comment]
Refs https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2419

**Comment by XWB** [comment]
Thanks.

**Comment by peterbxyz** [comment]
I added the translation for that new line as well.

Anyway is it a good idea to have a dot at the end of this line : "To finish activating your account - please visit %confirmationUrl%."? Email clients can mix this into the URL.

**Pull request merged**
