### PR TITLE
Added php-cs-fixer to format and check code

### PR DESCRIPTION
**Pull request by core23**
Increases code quality by using the php-cs-fixer and executes it while running travis ci.

### CODE REVIEW

**Comment by core23** [comment]
Depends on https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2242

**Comment by XWB** [comment]
@core23 https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2242 and https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2253 have been merged, can you rebase?

**Comment by core23** [comment]
Done @XWB

**Comment by OskarStark** [comment]
Good job @core23 👍

**Pull request merged**
