### PR TITLE
Update Mailer.php

### PR DESCRIPTION
**Pull request by rumours86**

### CODE REVIEW

**Comment by XWB** [comment]
Please also fix the CS issue :)

**Comment by XWB** [comment]
This PR can be combined with the other one https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2554

**Comment by rumours86** [comment]
> Please also fix the CS issue :)
How i can make it?

**Comment by XWB** [comment]
Code standard. This:

```
    /**
     * @param string $renderedTemplate
     * @param array|string $fromEmail
     * @param string $toEmail
     */
```

Should become this:

```
    /**
     * @param string          $renderedTemplate
     * @param array|string    $fromEmail
     * @param string          $toEmail
     */
```

**Comment by XWB** [comment]
Thanks.

**Pull request merged**
