### PR TITLE
Changed template paths to conform to Symfony best practices

### PR DESCRIPTION
**Pull request by dborsatto**
This was partially done in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2200, although according to [Symfony best pratices](http://symfony.com/doc/current/best_practices/templates.html#template-locations), even directories must have their names in lowercased snake_case.

### CODE REVIEW

**Comment by core23** [comment]
Not sure if this applies to controller directories. AFAIK this was meant for explicit directories.

**Comment by dborsatto** [comment]
The examples in the best practices guide show this being used for directories as well -- and they also explicitly mention it in a rule in the section I linked.

**Comment by XWB** [comment]
The examples say:

> AcmeDemoBundle:Default:subdir/index.html.twig

Capitalize for bundle templates. And:

> default/subdir/index.html.twig

Lowercase for templates stored in app/

**Comment by dborsatto** [comment]
In my interpretation, that table was more of a "what used to be the norm vs what we suggest as best practice", with the explicit rule "_Use lowercased snake_case for **directory** and template names_" to be used as a rule of thumb overall, also for vendor bundles. The current behavior would also result in a weird mix of capitalized camelCase (overriding vendors) and snake_case (for actual app templates) in app/Resources.

It would be interesting to have an "official" opinion on the matter.

**Comment by XWB** [comment]
What does Symfony itself use?

**Comment by Ener-Getick** [comment]
@XWB symfony [uses the uppercased version](https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/TwigBundle/Resources/views), so i'd say let's keep it as is.

**Comment by dborsatto** [comment]
I think it's a bit counter intuitive, but if that's what they do, that's the official way :) This PR can then be closed, I think.

**Pull request closed without merging**
