### PR TITLE
removed extra dot in english translation

### PR DESCRIPTION
**Pull request by domgraziano**
this was causing confirmation token sent in the link for to newly registered user to be wrong

### CODE REVIEW

**Comment by XWB** [comment]
Thanks.

**Comment by Laurent3170** [comment]
I won't cry for a dot, but it seems to me, that there should be one, as it's the end of the sentence ;-)

**Comment by domgraziano** [comment]
@Laurent3170 that dot was removed because it was causing the confirmation token link to be wrong. I noticed it when I updated FOSUserBundle to the latest version and I was getting errors while testing user confirmation.

**Comment by Laurent3170** [comment]
It looks "bizzare" that the dot does this, as it was after the`%` sign.
What about other languages?

**Comment by domgraziano** [comment]
I've briefly checked other languages and found the dot only in the english version, and thought another reason that was the cause since I was running with english translations. After removing it the token was working correctly again, therefore submitted this.

**Comment by Laurent3170** [comment]
Ok. The dot is there in french and never noticed any problem even with english. Let's leave it as it is...

**Comment by domgraziano** [comment]
@Laurent3170 well you are right the dot is in the french translation, but bear in mind it can causes trouble. The fact you never noticed it doesn't exclude the scenario where the error can be possible.
 
In order:

I tried to revert back the dot to see if I missed something but I haven't. 

The following is what I get re-introducing the dot (see the dot at the end of 
HTML:
<a href="http://vm.run/register/confirm/djWAUO98AJQOXnvSOoPph1n9v8CY_dffOat4UtQUprQ." target="_blank">http://su-oauth.d8-dgraziano.edo.run/register/confirm/djWAUO98AJQOXnvSOoPph1n9v8CY_dffOat4UtQUprQ.</a>

Plain text:
To finish activating =
your account - please visit http://vm.run/register/c=
onfirm/djWAUO98AJQOXnvSOoPph1n9v8CY_dffOat4UtQUprQ.

Basically I think is down to the mail client you use and how it translate the text to html. If you're using translation and txt mail by default, the dot (being a valid url character) can be interpreted by the mail client as part of the url and causing the error. This is the case with Mailhog for example.

I've also noticed that in the previous version of the bundle the dot was not there and by upgrading I started getting the error (that's why I have removed it) see here:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/v1.3.7/Resources/translations/FOSUserBundle.en.yml#L56

So to keep compatibility with every mail client I would not re-introduce the dot. 
As you said I won't cry for a dot but someone might will have trouble depending on which mail client is using. 

Cheers
D.

**Comment by Laurent3170** [comment]
@domgraziano thanks for your explanation. You're right I haven't think of this. I'll remove it from french.

**Comment by stof** [comment]
@Laurent3170 @domgraziano the dot can indeed cause issues depending of how the tool converting the plain-text email to HTML with link detects the URL. In the example given by @domgraziano above, the dot was included in the URL

**Pull request merged**
