### PR TITLE
fix gitignore

### PR DESCRIPTION
**Pull request by ruslan-naryzhnyi**
add to gitignore
```
.idea
.DS_Store
```

### CODE REVIEW

**Comment by core23** [comment]
👎 This are only platform files

**Comment by ruslan-naryzhnyi** [comment]
It's not conveniently make a commit in PhpStorm.
Btw, it exists in [SonataUserBundle ](https://github.com/sonata-project/SonataUserBundle/blob/3.x/.gitignore) and [SonataAdminBundle](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.gitignore)

**Comment by xabbuh** [comment]
@ruslan-naryzhnyi Other developers use other IDEs. Ignoring all special files for all of them is not the right way. Instead you can ignore these patterns in a global gitignore file on your own system to not have to exclude them in each project over and over again.

**Comment by ruslan-naryzhnyi** [comment]
ok, I've understood you

**Comment by core23** [comment]
> Btw, it exists in SonataUserBundle and SonataAdminBundle

Thanks for the hint, we should remove it

**Pull request closed without merging**
