### PR TITLE
considering users who disable CSRF protection for Symfony

### PR DESCRIPTION
**Pull request by gondo**
User can disable CSRF protection globally in the framework via `framework.csrf_protection.enabled: false`

### CODE REVIEW

**Comment by xabbuh** [comment]
What about updating the template to to only render the hidden field if a CSRF token is present?

**Comment by gondo** [comment]
@xabbuh wouldn't work. if you disable CSRF globally, Symfony does not create service `security.csrf.token_manager'` therefore `$this->get('security.csrf.token_manager')` is throwing exception. I've just spend some time tracing broken build, after this update.

**Comment by xabbuh** [comment]
@gondo I did not mean to update the template instead of this change, but doing it in addition to your current change. Sorry if that was not clear enough.

**Comment by gondo** [comment]
@xabbuh: I see. template is not breaking the build, this is. therefore it is critical to get this merged asap. any cosmetic change, such as updating template, can be done later. please do not delay this.
personally I am using custom template, therefore I don't really care.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/views/Security/login_content.html.twig#L8

This would render `<input type="hidden" name="_csrf_token" value="null" />`, maybe we can put `{if csrf_token}` around it?

**Comment by gondo** [comment]
@XWB sure. unfortunately i don't know how to squash 2 pull request via github UI. I can create another pull request if you want?

**Comment by XWB** [comment]
@gondo You can push another commit to this PR, github can automatically squash them.

**Comment by gondo** [comment]
@XWB no idea how to do that. I simply go to the file, click edit and then follow clicking green buttons. I've done #2270.

**Comment by XWB** [comment]
:+1:

**Comment by xabbuh** [comment]
@gondo On your own fork, choose the branch the PR is associated with and edit the desired file. This will create a new commit that is automatically reflected in the PR based on that branch.

**Pull request merged**
