### PR TITLE
Remove "from_email" default values

### PR DESCRIPTION
**Pull request by XWB**
Alternative https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2357

### CODE REVIEW

**Comment by dompie** [comment]
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The child node "from_email" at path "fos_user" must be configured.

**Comment by dompie** [comment]
So, I believe many people get the following exception now:

`                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The child node "from_email" at path "fos_user" must be configured.             
                                                                                 
`

**Comment by dompie** [comment]
I want to use the global confirmation Address for the confirmation E-Mail. See [documentation](https://symfony.com/doc/master/bundles/FOSUserBundle/configuration_reference.html). How to accomplish that now? Leaving this field empty throws the following error in Symfony:

```
                                                                  
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The child node "from_email" at path "fos_user" must be configured.             
                                                                                 
```

**Comment by dompie** [comment]
Ah, ok thx. I got the path wrong - it's **fos_user**

**Comment by alexislefebvre** [comment]
Maybe this should be documented in the [CHANGELOG](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Changelog.md)?

**Comment by XWB** [comment]
Changelog will be updated before we release the next beta.

**Comment by stevechilds** [comment]
@XWB - There's no mention in the changelog about this.

What is the config setting to replicate the previous default settings set in code?

**Pull request merged**
