### PR TITLE
REGISTRATION_FORM_INITIALIZE event

### PR DESCRIPTION
**Pull request by ncmf**
The REGISTRATION_FORM_INITIALIZE event occurs when the registration form is initialized.
This event allows you to modify registration form after registration process is initialized.

### CODE REVIEW

**Comment by ncmf** [comment]
@stof please review

**Comment by ncmf** [comment]
An additional opportunity to change the form. Another way.

**Comment by stof** [comment]
Well, we *already* have a supported way to change it. Adding another way to achieve the same only makes things more confusing (which one should I use ?) and increases the maintenance cost for us (we have to maintain this extra extension point).

**Comment by XWB** [comment]
Closing as this would add duplicate functionality.

**Pull request closed without merging**
