### PR TITLE
Bump the default minimal password length to 8 characters

### PR DESCRIPTION
**Pull request by denischatelain**
Bump the default minimal password length to 8 characters

### CODE REVIEW

**Comment by XWB** [comment]
I'm afraid this would result in a BC break.

**Comment by denischatelain** [comment]
To the best of my knowledge it would not create a BC break, as users using a two characters passwords (or possibly no password if the user was created from the command line) would still be able to log in. 
However, I do agree this would be a change of the default password policy which could need explaining and documenting

**Comment by XWB** [comment]
@denischatelain Would you be able to add a note to the documentation?

**Comment by axzx** [comment]
Why 8 characters? 
Maybe 6 characters is enough?

**Comment by XWB** [comment]
@axzx I believe 8 is considered to be best practice.

**Comment by XWB** [comment]
Thanks @denischatelain

**Comment by axzx** [comment]
@artemdigi 
> How to overrive min length?
> 
> https://symfony.com/doc/3.4/bundles/override.html#validation-metadata is not working...

You can put field $plainPassword in your User entity

```php
    /**
     * @var string
     *
     * @Assert\Regex(
     *     pattern="$((?=(.*\d){2,})(?=.*[a-z]).{8,})$",
     *     message="user_password_strong"
     * )
     */
    protected $plainPassword;
```

**Comment by stof** [comment]
this will still change the existing validation rule for all existing project (and so changing their business logic)

**Comment by gustawdaniel** [comment]
@axzx In my case your method allow to append new validation rule, not override old one

screenshot from 2019-01-16 16-49-33

First message is from your code, second is from this commit. I can agree that 8 letter password is best practice, but what with backward compatibility? I think that if Breaking Change is merged it should be documented better.

**Pull request merged**
