### PR TITLE
Update FOSUserBundle.ru.yml

### PR DESCRIPTION
**Pull request by andrewsmm**
Fix translate Bad credentials

### CODE REVIEW

**Comment by aivus** [comment]
:+1:

**Comment by aivus** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/friendsofsymfony/fosuserbundle/1750)

Reviewed files:
- Resources/translations/FOSUserBundle.ru.yml @ r1





---

**Comment by mhor** [comment]
FYI, this change has been proposed in the past and was rejected (see #1559).

**Comment by XWB** [comment]
See https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1559

**Pull request closed without merging**
