### PR TITLE
Maintain Naming Convention for templates

### PR DESCRIPTION
**Pull request by jigarpancholi**
- Rename templates name to underscore case. https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2193

### CODE REVIEW

**Comment by XWB** [comment]
Thanks.

**Comment by gondo** [comment]
OMG! another code breaking merge without ANY note or bumping the version.
some people do use templates overwrite and this completely break the code

**Comment by core23** [comment]
It's merged into the 2.0 branch, so BC breaks are allowed

**Comment by stof** [comment]
@gondo and we *will* mention it in the changelog when doing a release. If you depend on dev-master, you cannot complain about changes not mentionned in the changelog, as we update it when releasing

**Pull request merged**
