### PR TITLE
Switched documentation from Markdown to reStructuredText

### PR DESCRIPTION
**Pull request by javiereguiluz**
This PR overrides #1717 and switches the documentation format to allow to integrate it in the new symfony.com doc section.

### CODE REVIEW

**Comment by stof** [comment]
@javiereguiluz I still want to convert the doc to rST in the 1.3.x branch, not only in master (1.3.x is still maintained)

**Comment by javiereguiluz** [comment]
I see. I thought that we could do the Git-magic that Symfony doc guys use to apply the changes to all maintained branches. What could I do to make this happen?

**Comment by stof** [comment]
@javiereguiluz the 'git magic' they do is doing the change in the older branch and then merging into newer branches.
For the conversion of the doc, this magic is failing, because the changes done in the master branch won't be converted magically by git to the new format.

I think the easier to migrate both branches might be to do the conversion fully in each branch (and then using the git merging again to apply doc enhancements in both branches). So can you reopen #1717 by fixing your rebase (doing it on top of 1.3.x) for the 1.3.x conversion ?

**Comment by stof** [comment]
@javiereguiluz ping

**Comment by stof** [comment]
@javiereguiluz ping

**Comment by rparsi** [comment]
@stof 
Given that the pr is still open and I'm having a devil of a time with current documentation looks like this went nowhere, unfortunately.

Formatting is not really the issue, it's missing pieces of information.  For example, currently I'm trying to track down the full list of events that's generated by either FOSUserBundle and SecurityBundle.

Why is getting this information so hard?  Seems like there should be an app/console command that dumps all the current "catchable" events, similar to how app/console debug:router works.  Hell I'll write one if I have to.

**Comment by stof** [comment]
@rparsi This PR is about converting the doc to rST to be able to have it displayed on symfony.com. discussion about the content of the doc is totally out of the scope of this PR.

And the feature you are asking about does not seem something for FOSUserBundle anyway. Thus, it would be really hard to implement as there is simply no registry of events (unlike routes for which we have the list of routes in the router). You can trigger any event you want. the only way I see would be to perform some static analysis of the codebase to locate any use of the event dispatcher (and then hoping that you don't have dynamic event names)

**Comment by stof** [comment]
Given there was no feed back, I re-did the conversion myself for the uptodate documentation:

- 95ec6c64102a37be85c196b147ffe2a7b20df691 for the 1.3.x branch
- 7523d11674568e39fa4b0023614de23acc72edfe for the master branch

**Pull request closed without merging**
