### PR TITLE
Removed support for older Doctrine versions

### PR DESCRIPTION
**Pull request by stof**
The minimal versions are now Doctrine Common 2.3, Doctrine ORM 2.4 and Doctrine MongoDB ODM 1.0-alpha10.

I just figured out that CouchDB does not yet rely on the Doctrine Common events yet, so I will need to change this partially (I was in the train when doing it, without access to github to check it).
I'm wondering whether I revert the removal of the CouchDB dedicated listener, or whether I update the ODM and try to convince @beberlei to release a new version instead. I don't know how many people use the CouchDB integration in the bundle.

### CODE REVIEW

**Comment by merk** [comment]
I'm not sure if it's just my weird setup in an older project, but the compiler is removing the fos_user.doctrine_registry alias even though it is being used by the ORM fos_user.object_manager service.

app/cache/de_/ap_DevDebugProjectContainerCompiler.log after a composer upgrade and a failed cache:clear:

Symfony\Component\DependencyInjection\Compiler\RemovePrivateAliasesPass: Removed service "fos_user.doctrine_registry"; reason: private alias

The service definition in app/cache/de_/ap_DevDebugProjectContainer.xml:

```
    <service id="fos_user.object_manager" class="Doctrine\Common\Persistence\ObjectManager" public="false">
      <argument>null</argument>
      <factory service="fos_user.doctrine_registry" method="getManager"/>
    </service>
```

**Comment by stof** [comment]
@merk this may be a bug in Symfony failing to detect that a factory is using the service (or failing to inline the factory itself)

**Comment by stof** [comment]
I'm planning another (hopefully for tomorrow evening but I cannot guarantee it) where I would inject the registry rather than the manager, which would keep the ORM lazy and would also be compatible with resetting the entity manager

**Comment by xabbuh** [comment]
see symfony/symfony#17554 for the fix in Symfony

**Pull request merged**
