### PR TITLE
Add compatibility with Symfony 5.3

### PR DESCRIPTION
**Pull request by ajgarlag**
I'm trying to make minimal changes to allow installation with Symfony 5.3 without introducing BC breaks.

Work in progress. Any feedback is welcome.

### CODE REVIEW

**Comment by stof** [comment]
This is a no-go for the 2.x branch, as it involves some BC breaks (changing the parent class of a class is a BC break)

**Comment by ajgarlag** [comment]
@stof Thanks for your comment.

I've rewritten the BC layer for event-dispatcher, so the parent class of events does not change if event-dispatcher:^4.4 is available.

**Comment by stof** [comment]
@ajgarlag I'm working on the master branch for a 3.0 version, which will include support for 5.3

**Comment by ajgarlag** [comment]
@stof I'd like to upgrade to Symfony 5.3 including the deprecated Group feature.

I think that branch 2.x could support Symfony 4/5, and master (future 3.x) could support Symfony 5/6.

**Comment by stof** [comment]
We cannot support Symfony 5 without breaking BC in the bundle

**Comment by ajgarlag** [comment]
Ok, I thought that my PR does not include BC breaks, but it looks that I'm wrong. Only two more questions:

* Will release 3.0 support Symfony 4.4?
* Do you have any estimated date to publish your commits including Symfony 5 support in the master branch?

**Comment by stof** [comment]
> * Will release 3.0 support Symfony 4.4?

yes

> * Do you have any estimated date to publish your commits including Symfony 5 support in the master branch?

tomorrow (and this should be reliable as I'm dedicated some work time to it rather than relying only on my free time)

**Comment by ajgarlag** [comment]
@stof. Thanks for your answers. I hope to see a stable release with Symfony 5.3 support soon.

**Comment by stof** [comment]
@ajgarlag for now, I have compatibility with Symfony 5, but not yet deprecation-free for 5.3 (I still need to handle the changes related to the new security system)

**Comment by stof** [comment]
Closing in favor of #3020 (and previous ones)

**Comment by ajgarlag** [comment]
@stof I've finally removed group feature usage from my app, and I've tested the master branch without issues. Is there any estimated date to release v3.0?

Maybe an `rc` version would help other people to test the master branch.

**Pull request closed without merging**
