### PR TITLE
Add PHP 7 on Travis

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by stof** [comment]
What is the different between  PHP 7 and PHP nightly on Travis currently ? they were aliases when the implemented it

**Comment by stof** [comment]
OK, they were still equivalent at the time your PR was running

**Comment by Soullivaneuh** [comment]
> OK, they were still equivalent at the time your PR was running

Yes. `nightly` will be interesting when PHP 7 will be stable.

**Comment by xabbuh** [comment]
I suggest to remove `nightly` then for now. It doesn't add any value, but removing it saves one job per pull request.

**Comment by Soullivaneuh** [comment]
@xabbuh @stof done.

**Comment by xabbuh** [comment]
:+1:

**Pull request merged**
