### PR TITLE
Resolves #2083

### LINKED ISSUE #2083: Fatal error when login route is accessed from app_dev.php
On Symfony 3:

When the login is accessed from `app_dev.php`, you get a `500 Server Error`

> Key "request" for array with keys "name" does not exist in FOSUserBundle::layout.html.twig

### PR DESCRIPTION
**Pull request by starx**
Added a check if the variable is defined

### CODE REVIEW

**Comment by xabbuh** [comment]
This does not seem to be necessary. The `Request` class from the Symfony HttpFoundation component defines this method.

**Comment by starx** [comment]
@xabbuh Before declaring it as unnecessary have you looked into the issue I quoted? I would not fix it, if there wasn't any error.

**Comment by xabbuh** [comment]
Did you replace the global `app` variable with something else in your project?

**Comment by starx** [comment]
@xabbuh No its a native project created symfony command. I didn't tamper with the `app*.php` files.

**Comment by xabbuh** [comment]
The global `app` variable is not related to the `app*.php` front controller files. It's global Twig variable defined by Symfony: http://symfony.com/doc/current/reference/twig_reference.html#app

**Comment by starx** [comment]
Either way, its a native Symfony project which I haven't modified. Do you a file I can check to make sure of this?

**Comment by XWB** [comment]
Well, `app.request` is always available, unless you have disabled it somehow.

**Pull request closed without merging**
