### PR TITLE
New FormType: UserChoice

### PR DESCRIPTION
**Pull request by lemoinem**
We often need to select a user, I think this would be quite useful when it cannot be achieved trivially using Doctrine's (or Propel)'s builtin form Type, or when the users are stored using some other method.

This FormType is strongly based on Doctrine's `entity` one.

### CODE REVIEW

**Comment by lemoinem** [comment]
Hello,

This PR is still useful to us and I would like to have a feedback on what the issue(s) of the PR are.

Is the idea itself not quite interesting, even considering the points raised in previous comments, or is it a matter of imperfect implementation?

In the latter case, I'm ready to take any comment on how to improve the implementation and make it mergeable.

**Comment by lemoinem** [comment]
@stof: Sorry for the personal ping, but since you provided most of the feedback during this PR life. I'm curious as to what you current opinion on this is. Once again if the issue is an imperfect implementation, I'm ready to act on any feedback to make it mergeable.

I would greatly appreciate if you had a few minutes available to look into this.

**Comment by raistlin** [comment]
:-1: I have around 5000 users on some symfony app, loading all of them to display at forms is not an option.

**Comment by XWB** [comment]
Agree with the guys above, therefore I'm closing this PR.

**Pull request closed without merging**
