### PR TITLE
Edit profile : implement email confirmation

### PR DESCRIPTION
**Pull request by b-durand**
We must confirm the new updated email when the option is enabled. References #949.
Initial commit.

### CODE REVIEW

**Comment by azine** [comment]
@lsmith77 or @stof: is there any progress on this issue? Will it be fixed or not? This should def. be core functionality.

**Comment by peshi** [comment]
@azine I have tried this example with MongoDB, Embedded Document with a Subform to store other information about the user. Additional data is not saved due to 'reloadUser'.

**Comment by azine** [comment]
@peshi: why do you tell me this? Which example are you talking about? I guess you meant someone else?

**Comment by peshi** [comment]
@azine Sorry, I was ment to address @b-durand - And I'm talking about this PR.

**Comment by fredleput** [comment]
Hi, i'm very interested in that functionality too thx for implementing it.

**Comment by XWB** [comment]
Closing this PR as it is outdated.

**Comment by azine** [comment]
For anyone still interested in the "update email confirmation" feature: as FOSUserBundle does not move, I we implemented this feature as separate bundle.
See https://github.com/azine/AzineEmailUpdateConfirmationBundle

**Pull request closed without merging**
