### PR TITLE
Redirect to login when using confirmation link more than once

### PR DESCRIPTION
**Pull request by Laurent3170**
As done in #2653, it will solve #2106, #2420 and #2644 and will give a more coherent/convenient way to treat this misuse of activation link

### CODE REVIEW

**Comment by XWB** [comment]
Thanks :)

**Comment by benjaminb-** [comment]
Still not available ?

**Comment by Laurent3170** [comment]
It should. I don't follow anymore as I have built my own UserProvider https://github.com/975L/UserBundle

**Comment by benjaminb-** [comment]
Okay sorry i didn't see the detail of your pull request is about checkEmailAction (the title was confusing). It could be the same for confirmAction #2763

**Comment by Laurent3170** [comment]
Yes you're right, in fact it should have been set in `confirmAction()` and not in `checkEmailAction()`... I think I was tired... I let you do the PR and correct back `checkEmailAction()`.

**Pull request merged**
