### PR TITLE
Add Symfony 5.4 compatibility for version 2.x with groups

### PR DESCRIPTION
**Pull request by andreclemente**
This pull request aims to keep the deprecated groups feature on this dependency and, at the same time, be able to upgrade the Symfony framework to version 5.4.

### CODE REVIEW

**Comment by andreclemente** [comment]
That's why the pull request is for 2.x...

**Comment by stof** [comment]
sorry, I meant `for 2.x` in my comment. The 2.x branch is not allowed to break BC compared to the existing 2.2.4 release.

**Comment by stof** [comment]
I'm closing this as it cannot be accepted. There is no way to add support for Symfony 5.4 in the 2.x branch without BC breaks (I tried that approach before doing a 3.0 release).

**Comment by andreclemente** [comment]
Can you describe the errors you get? It works on my side...

**Pull request closed without merging**
